// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQLqSYLORKqfy-9rYBgS8E41SWxUEN-8Q',
    appId: '1:225329482961:web:882fc8d801fe3a0a1209f0',
    messagingSenderId: '225329482961',
    projectId: 'genui-task-list-app',
    authDomain: 'genui-task-list-app.firebaseapp.com',
    storageBucket: 'genui-task-list-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4vDMbORktrMWkQF7CuMzumdZd7w5HvX8',
    appId: '1:225329482961:android:99cb3377c7d792b31209f0',
    messagingSenderId: '225329482961',
    projectId: 'genui-task-list-app',
    storageBucket: 'genui-task-list-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGCVV0ccPtIns23aRDd4vWRLVxp1gjg5I',
    appId: '1:225329482961:ios:c895ac7409ad76a11209f0',
    messagingSenderId: '225329482961',
    projectId: 'genui-task-list-app',
    storageBucket: 'genui-task-list-app.firebasestorage.app',
    iosBundleId: 'com.example.genuiTaskListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGCVV0ccPtIns23aRDd4vWRLVxp1gjg5I',
    appId: '1:225329482961:ios:c895ac7409ad76a11209f0',
    messagingSenderId: '225329482961',
    projectId: 'genui-task-list-app',
    storageBucket: 'genui-task-list-app.firebasestorage.app',
    iosBundleId: 'com.example.genuiTaskListApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQLqSYLORKqfy-9rYBgS8E41SWxUEN-8Q',
    appId: '1:225329482961:web:d0e5edb5bc1713431209f0',
    messagingSenderId: '225329482961',
    projectId: 'genui-task-list-app',
    authDomain: 'genui-task-list-app.firebaseapp.com',
    storageBucket: 'genui-task-list-app.firebasestorage.app',
  );
}
